### ISSUE TITLE
Text 的 fontSize hook 失败，回调不执行

### ISSUE THREAD

**Issue by AppleDP** [HuolalaTech/AspectPro#1]
<img width="856" alt="图片" src="https://github.com/user-attachments/assets/56b3084e-8df8-4fdc-b8f3-76fa20e85609">

**Comment by GkLwPp** [comment]
最后一个参数传false或者不传即可(默认false)， 只有Button#onClick(clickEvent) 需要hook clickEvent场景最后一个参数才需要传true。
![image](https://github.com/user-attachments/assets/680f1995-53be-411d-87df-3c27872e648a)
